name: Noficicação no Discord

on:
  push:
    branches:
        - main

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do código 
              uses: actions/checkout@v2

            - name: Obter mensagem do commit 
              id: commit 
              run: |
                echo "msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
                echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Enviar notificação para o Discord
              env:
                 DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                 username: 'GitHub Actions'
                 avatar-url: 'https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg'
              uses: Ilshidur/action-discord@master
              with:
                 args: |
                   **Novo commit no repositório!**
                   - Mensagem: ${{ steps.commit.outputs.msg }}
                   - SHA: ${{ steps.commit.outputs.sha }}